services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: docker.arvancloud.ir/postgres:16
    restart: always
    user: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      # - "POSTGRES_HOST_AUTH_METHOD=trust"
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGUSER: postgres
      POSTGRES_HOST: 127.0.0.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "django"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  adminer:
    image: docker.arvancloud.ir/adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres_data: